### ISSUE TITLE
Does not start in Arclight for 1.18

### ISSUE THREAD

**Issue by soystargaze** [Ehhthan/MMOBuffs-Wiki#6]
07.03 18:16:54 [Server] INFO [MMOBuffs]: Enabling MMOBuffs v1.2.2
07.03 18:16:54 [Server] ERROR [Minecraft]: Error occurred while enabling MMOBuffs v1.2.2 (Is it up to date?)
07.03 18:16:54 [Server] INFO java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/tag/resolver/TagResolver
07.03 18:16:54 [Server] INFO at com.ehhthan.mmobuffs.manager.type.EffectManager.reload(EffectManager.java:19) ~[?:?]
07.03 18:16:54 [Server] INFO at com.ehhthan.mmobuffs.manager.type.EffectManager.<init>(EffectManager.java:10) ~[?:?]
07.03 18:16:54 [Server] INFO at com.ehhthan.mmobuffs.MMOBuffs.onEnable(MMOBuffs.java:54) ~[?:?]
07.03 18:16:54 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at net.minecraft.server.MinecraftServer.handler$bhh000$arclight$enablePlugins(MinecraftServerMixin.java:2217) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
07.03 18:16:54 [Server] INFO at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:403) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
07.03 18:16:54 [Server] INFO at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:316) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
07.03 18:16:54 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:173) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
07.03 18:16:54 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
07.03 18:16:54 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?]
07.03 18:16:54 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
07.03 18:16:54 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.tag.resolver.TagResolver
07.03 18:16:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:147) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
07.03 18:16:54 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
07.03 18:16:54 [Server] INFO ... 15 more

**Comment by Ehhthan** [comment]
Make sure you are running the latest paper build for your version

**Comment by soystargaze** [comment]
Should I use Magma instead of Arclight then? It has better compatibility with Paper

**Comment by soystargaze** [comment]
07.03 19:11:43 [Server] Server thread/ERROR Error occurred while enabling MMOBuffs v1.2.2 (Is it up to date?)
07.03 19:11:43 [Server] INFO java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/tag/resolver/TagResolver
07.03 19:11:43 [Server] INFO at com.ehhthan.mmobuffs.manager.type.EffectManager.reload(EffectManager.java:19) ~[?:?] {}
07.03 19:11:43 [Server] INFO at com.ehhthan.mmobuffs.manager.type.EffectManager.<init>(EffectManager.java:10) ~[?:?] {}
07.03 19:11:43 [Server] INFO at com.ehhthan.mmobuffs.MMOBuffs.onEnable(MMOBuffs.java:54) ~[?:?] {}
07.03 19:11:43 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:?] {re:mixin,re:classloading,re:mixin,re:mixin}
07.03 19:11:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:415) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:?] {re:classloading,re:mixin}
07.03 19:11:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:?] {re:classloading}
07.03 19:11:43 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:477) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:7e29f765-296df566-9fb885e8] {re:classloading}
07.03 19:11:43 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:7e29f765-296df566-9fb885e8] {re:classloading}
07.03 19:11:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:447) ~[server-1.18.2-20220404.173914-srg.jar%23215!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
07.03 19:11:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:358) ~[server-1.18.2-20220404.173914-srg.jar%23215!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
07.03 19:11:43 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:252) ~[server-1.18.2-20220404.173914-srg.jar%23215!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
07.03 19:11:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:841) ~[server-1.18.2-20220404.173914-srg.jar%23215!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
07.03 19:11:43 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:257) ~[server-1.18.2-20220404.173914-srg.jar%23215!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.excavated_variants.json:IMinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
07.03 19:11:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
07.03 19:11:43 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.tag.resolver.TagResolver
07.03 19:11:43 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:174) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:?] {re:classloading}
07.03 19:11:43 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[forge-1.18.2-40.2.1-universal.jar%23220!/:?] {re:classloading}
07.03 19:11:43 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
07.03 19:11:43 [Server] INFO ... 14 more

**Comment by soystargaze** [comment]
Same error with the last Magma

**Comment by Ehhthan** [comment]
You need to use a modern paper implementation.
